README.md
src/main/java/ai/promoted/delivery/client/ApiDelivery.java
src/main/java/ai/promoted/delivery/client/ApiFactory.java
src/main/java/ai/promoted/delivery/client/DefaultApiFactory.java
src/main/java/ai/promoted/delivery/client/DeliveryRequestState.java
src/main/java/ai/promoted/delivery/client/InsertionFactory.java
src/main/java/ai/promoted/delivery/client/PromotedDeliveryClient.java
src/main/java/ai/promoted/delivery/client/SdkDelivery.java
src/test/java/ai/promoted/delivery/client/DeliveryRequestStateTest.java
src/test/java/ai/promoted/delivery/client/InsertionFactoryTest.java
src/test/java/ai/promoted/delivery/client/PromotedDeliveryClientTest.java
src/test/java/ai/promoted/delivery/client/SdkDeliveryTest.java
src/test/java/ai/promoted/delivery/client/TestApiFactory.java
src/test/java/ai/promoted/delivery/client/TestUtils.java

@danbosnichill let me know what you think of this approach, and I can apply it elsewhere.

Max request insertions

---

pom.xml

Unfortunately it won't complete if you have local mods (including to pom.xml here), so I need to merge this before fully trying it out.

Try the release plugin

---

pom.xml

This is giving an error during release

Add missing repository section to distributionManagement

---

src/main/java/ai/promoted/delivery/client/DefaultDeliveryRequestValidator.java
src/test/java/ai/promoted/delivery/client/DeliveryRequestTest.java

Found this while working on Python, looks problematic.

Validate delivery request has inner request

---

README.md
pom.xml
src/main/java/ai/promoted/delivery/client/Sampler.java

The instructions say to change the pom version to be the next patch release.  I'm not sure why though.
I burned through a few patches and don't know enough to remove them.

feat: release 0.0.9

---

README.md
src/main/java/ai/promoted/delivery/client/DefaultDeliveryRequestValidator.java
src/main/java/ai/promoted/delivery/model/UserInfo.java
src/test/java/ai/promoted/delivery/client/DeliveryRequestTest.java
src/test/java/ai/promoted/delivery/client/IntegrationTest.java

PRO-5544
BREAKING CHANGE: renames an existing field.
TESTING=ran existing tests

feat: rename logUserId to anonUserId

---

README.md
pom.xml

PRO-5544
I hit a bunch of issues getting this to work again.  I wanted to record better notes.
TESTING=Already applied.

docs: update deploy instructions

---

README.md
src/main/java/ai/promoted/delivery/client/DefaultDeliveryRequestValidator.java
src/main/java/ai/promoted/delivery/client/DeliveryRequest.java
src/main/java/ai/promoted/delivery/client/SdkDelivery.java
src/test/java/ai/promoted/delivery/client/DeliveryRequestTest.java
src/test/java/ai/promoted/delivery/client/SdkDeliveryTest.java

BREAKING CHANGE: renames the insertionStart field.
TESTING=ran existing tests

refactor: rename field to retrievalInsertionOffset

---

README.md

docs: update executor example

---

src/main/java/ai/promoted/delivery/client/ApiDelivery.java

I hit this when working on the example client.
TESTING=ran existing tests

feat: log warmup exception

---

src/main/java/ai/promoted/delivery/client/ApiDelivery.java
src/main/java/ai/promoted/delivery/client/ApiMetrics.java

PRO-5656
TESTING=manuallly used similar code in a different binary

fix: remove nulls from Request and LogRequest

---

pom.xml
src/main/java/ai/promoted/delivery/client/PromotedDeliveryClient.java

feat: bump version to 2.0.3

---

src/main/java/ai/promoted/delivery/client/PromotedDeliveryClient.java
src/main/java/ai/promoted/delivery/model/ClientType.java
src/test/java/ai/promoted/delivery/client/PromotedDeliveryClientTest.java

PRO-5656
Looks like this breaks Delivery.
TESTING=ran unit tests

fix: enum value

---

README.md

docs: add example github link

---

pom.xml
src/main/java/ai/promoted/delivery/client/PromotedDeliveryClient.java

feat: bump version to 2.1.0

---

README.md
src/main/java/ai/promoted/delivery/model/Request.java

feat: add Request.disablePersonalization

---

src/main/java/ai/promoted/delivery/client/SdkDelivery.java
src/test/java/ai/promoted/delivery/client/PromotedDeliveryClientTest.java

fix: insertion id plumbing

---

README.md
pom.xml
src/main/java/ai/promoted/delivery/client/PromotedDeliveryClient.java

I forgot to update the embedded version.

feat: update version; improve instructions

---

README.md

docs: update experiment example

---

src/main/java/ai/promoted/delivery/client/ApiDelivery.java
src/test/java/ai/promoted/delivery/client/ApiDeliveryTest.java

Will need the suffix-less endpoint for gRPC

Change endpoint handling in ApiDelivery

---

pom.xml
src/main/java/ai/promoted/delivery/client/PromotedDeliveryClient.java

TESTING=already built using this.

feat: update version to 3.1.1
